-- MySQL Script generated by MySQL Workbench
-- Tue Jun 25 13:29:12 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema academia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `academia` DEFAULT CHARACTER SET utf8 ;
USE `academia` ;

-- -----------------------------------------------------
-- Table `academia`.`servicos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`servicos` (
  `id_servicos` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `preco` FLOAT NOT NULL,
  PRIMARY KEY (`id_servicos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`cargo` (
  `id_cargo` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  `salario` FLOAT NOT NULL,
  `atribuicoes` VARCHAR(100) NULL,
  PRIMARY KEY (`id_cargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`terceiros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`terceiros` (
  `id_terceiro` INT NOT NULL AUTO_INCREMENT,
  `cpf_cnpj` VARCHAR(45) NULL,
  `nome_razao_social` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `e_mail` VARCHAR(45) NULL,
  PRIMARY KEY (`id_terceiro`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf_cnpj` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`funcionario` (
  `id_func` INT NOT NULL AUTO_INCREMENT,
  `data_admissao` DATE NOT NULL,
  `data_demissao` DATE NOT NULL,
  `id_terceiro` INT NOT NULL,
  `id_cargo` INT NOT NULL,
  PRIMARY KEY (`id_func`),
  UNIQUE INDEX `cpf_UNIQUE` (`data_admissao` ASC) ,
  INDEX `fk_func_terc_idx` (`id_terceiro` ASC) ,
  CONSTRAINT `fk_func_cargo`
    FOREIGN KEY (`id_cargo`)
    REFERENCES `academia`.`cargo` (`id_cargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_func_terc`
    FOREIGN KEY (`id_terceiro`)
    REFERENCES `academia`.`terceiros` (`id_terceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`cliente` (
  `codigo` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(45) NOT NULL,
  `terceiros_id_cliente` INT NOT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `fk_cliente_terceiros1_idx` (`terceiros_id_cliente` ASC) ,
  UNIQUE INDEX `terceiros_id_cliente_UNIQUE` (`terceiros_id_cliente` ASC),
  CONSTRAINT `fk_cliente_terceiros1`
    FOREIGN KEY (`terceiros_id_cliente`)
    REFERENCES `academia`.`terceiros` (`id_terceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`contrato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`contrato` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `venc_fatura` DATE NULL,
  `id_servicos` INT NOT NULL,
  `id_funcionario` INT NOT NULL,
  `codigo_cliente` INT NOT NULL,
  PRIMARY KEY (`id_contrato`),
  INDEX `fk_contrato_servicos_idx` (`id_servicos` ASC) ,
  INDEX `fk_contrato_func_idx` (`id_funcionario` ASC) ,
  INDEX `fk_contrato_cliente_idx` (`codigo_cliente` ASC) ,
  CONSTRAINT `fk_contrato_servicos`
    FOREIGN KEY (`id_servicos`)
    REFERENCES `academia`.`servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_func`
    FOREIGN KEY (`id_funcionario`)
    REFERENCES `academia`.`funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_cliente`
    FOREIGN KEY (`codigo_cliente`)
    REFERENCES `academia`.`cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`turma` (
  `id_turma` INT NOT NULL AUTO_INCREMENT,
  `horario` VARCHAR(30) NOT NULL,
  `turno` VARCHAR(45) NOT NULL,
  `qtd_vagas` INT NOT NULL,
  `id_servicos` INT NOT NULL,
  PRIMARY KEY (`id_turma`),
  INDEX `fk_turma_serv_idx` (`id_servicos` ASC) ,
  CONSTRAINT `fk_turma_serv`
    FOREIGN KEY (`id_servicos`)
    REFERENCES `academia`.`servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`aluno` (
  `matricula` INT NOT NULL AUTO_INCREMENT,
  `id_terceiros` INT NOT NULL,
  `id_turma` INT NOT NULL,
  PRIMARY KEY (`matricula`),
  INDEX `fk_aluno_terceiros1_idx` (`id_terceiros` ASC) ,
  INDEX `fk_aluno_turma1_idx` (`id_turma` ASC),
  UNIQUE INDEX `matricula_UNIQUE` (`matricula` ASC) ,
  CONSTRAINT `fk_aluno_terceiros1`
    FOREIGN KEY (`id_terceiros`)
    REFERENCES `academia`.`terceiros` (`id_terceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_aluno_turma1`
    FOREIGN KEY (`id_turma`)
    REFERENCES `academia`.`turma` (`id_turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`endereco` (
  `id_end` INT NOT NULL AUTO_INCREMENT,
  `pais` VARCHAR(45) NOT NULL,
  `uf` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(100) NOT NULL,
  `numero` VARCHAR(15) NOT NULL,
  `id_terceiro` INT NULL,
  PRIMARY KEY (`id_end`),
  INDEX `fK_endereco_terceiros_idx` (`id_terceiro` ASC) ,
  CONSTRAINT `fK_endereco_terceiros`
    FOREIGN KEY (`id_terceiro`)
    REFERENCES `academia`.`terceiros` (`id_terceiro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `academia`.`servicos_funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `academia`.`servicos_funcionario` (
  `servicos_id_servicos` INT NOT NULL,
  `funcionario_id_func` INT NOT NULL,
  `id_serv_func` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_servicos_has_funcionario_funcionario1_idx` (`funcionario_id_func` ASC) ,
  INDEX `fk_servicos_has_funcionario_servicos1_idx` (`servicos_id_servicos` ASC) ,
  PRIMARY KEY (`id_serv_func`),
  UNIQUE INDEX `id_serv_func_UNIQUE` (`id_serv_func` ASC) ,
  CONSTRAINT `fk_servicos_has_funcionario_servicos1`
    FOREIGN KEY (`servicos_id_servicos`)
    REFERENCES `academia`.`servicos` (`id_servicos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_servicos_has_funcionario_funcionario1`
    FOREIGN KEY (`funcionario_id_func`)
    REFERENCES `academia`.`funcionario` (`id_func`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
